cusvar: cm
cm:
#  env: dev
  env: prod
  spider:
    enabled: true
    loginTip:
      inteval: 10
      email:
        fromAddress: 22123971@qq.com
        username: 22123971@qq.com
        password: Wwkkvikthh123
        ssl: true
        smtpPort: 23
  divvy:
#    username: 22123971@qq.com
#    username: 2673794381@qq.com
    username: contac@ziteusa.com
#    password: Wwkkvikthh1234
    password: Cavy996633!
    budget:
#      id: QnVkZ2V0OjQ3MzAz
#      id: QnVkZ2V0OjQ5MTQ2
      id: QnVkZ2V0OjYzMzU2
#      ownerId: VXNlcjo1MTIzNg==
#      ownerId: VXNlcjo1MTE5OA==
      ownerId: VXNlcjo3MjM2MQ==
    company:
#      id: Q29tcGFueTozMDI3
      id: Q29tcGFueTozODI0
  epaylinks:
    username: 13066349373
    password: Cavy5201!
    email:
      username: 2673794381@qq.com
      password: plu996633
      host: mail.qq.com
      port: 23
  constant:
    secAdminStr: secAdmin
mybatis:
  #  # @MyBatisDao、Aliases 扫描基础包，如果多个，用“,”分隔
  scanBasePackage: com.jeesite.modules,com.ralf.cardmanager
  # TypeHandlers 扫描基础包，如果多个，用“,”分隔
  scanTypeHandlersPackage: ~

  # Mapper文件刷新线程
  mapper:
    refresh:
      enabled: true
      delaySeconds: 60
      sleepSeconds: 3
      mappingPath: mappings
session:
  #
  #  # 全局会话超时，单位：毫秒， 20m=1200000ms, 30m=1800000ms, 60m=3600000ms, 12h=43200000ms, 1day=86400000ms
  sessionTimeout: 86400000
  #
  #  # 手机APP设备会话超时参数设置，登录请求参数加 param_deviceType=mobileApp 时有效
  #  mobileAppSessionTimeout: 43200000
  #
  #  # 定时清理失效会话，清理用户直接关闭浏览器造成的孤立会话
  #  sessionTimeoutClean: 1200000
  #
  #  # 会话唯一标识SessionId在Cookie中的名称。
  sessionIdCookieName: cm.session.id
#======================================#
#========== Server settings ===========#
#======================================#
server:
  port: 8980
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8