package com.ralf.cardmanager.spider.task.divvypay.operation.cardoperation;

import com.ralf.cardmanager.spider.task.divvypay.config.DivvyPaySiteConfig;
import com.ralf.cardmanager.spider.task.divvypay.operation.base.BaseDivvyOperation;
import com.ralf.cardmanager.spider.task.divvypay.operation.base.BaseDivvyOpertionResp;
import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

@Service
@Scope("prototype")
public class SetBudgetCardRecurring extends BaseDivvyOperation<SetBudgetCardRecurringRsp> {
    public SetBudgetCardRecurring(DivvyPaySiteConfig config) {
        super(config);
        body = "{\"operationName\":\"GetBudgetForecast\",\"variables\":{\"budgetId\":\"%s\",\"first\":5000},\"query\":\"query GetBudgetForecast($budgetId: ID!, $first: Int!) {\\n  node(id: $budgetId) {\\n    ... on Budget {\\n      id\\n      recurringAmount\\n      type\\n      currentGoal\\n      ...BudgetHeaderChart\\n      allCards(first: $first, types: [SUBSCRIPTION, BURNER]) {\\n        edges {\\n          node {\\n            id\\n            lastFour\\n            cardType\\n            latestTransaction {\\n              id\\n              merchantName\\n              __typename\\n            }\\n            name\\n            userAllocation {\\n              id\\n              recurringAmount\\n              balance\\n              type\\n              expiresAt\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      users(first: $first) {\\n        edges {\\n          role\\n          node {\\n            id\\n            avatarUrl\\n            displayName\\n            firstName\\n            lastName\\n            allocations(first: 1, budgetId: $budgetId) {\\n              edges {\\n                node {\\n                  id\\n                  recurringAmount\\n                  balance\\n                  type\\n                  __typename\\n                }\\n                __typename\\n              }\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment BudgetHeaderChart on Budget {\\n  id\\n  currentGoal\\n  expiresAt\\n  recurringAmount\\n  shareBudgetFunds\\n  totalClearedForBudgetPeriod\\n  totalDivviedForBudgetPeriod\\n  totalPendingForBudgetPeriod\\n  type\\n  __typename\\n}\\n\"}";
//        body = "{\"operationName\":\"GetBudgetForecast\",\"variables\":{\"budgetId\":\"QnVkZ2V0OjQ5MTQ2\",\"first\":5000},\"query\":\"query GetBudgetForecast($budgetId: ID!, $first: Int!) {\\n  node(id: $budgetId) {\\n    ... on Budget {\\n      id\\n      recurringAmount\\n      type\\n      currentGoal\\n      ...BudgetHeaderChart\\n      allCards(first: $first, types: [SUBSCRIPTION, BURNER]) {\\n        edges {\\n          node {\\n            id\\n            lastFour\\n            cardType\\n            latestTransaction {\\n              id\\n              merchantName\\n              __typename\\n            }\\n            name\\n            userAllocation {\\n              id\\n              recurringAmount\\n              balance\\n              type\\n              expiresAt\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      users(first: $first) {\\n        edges {\\n          role\\n          node {\\n            id\\n            avatarUrl\\n            displayName\\n            firstName\\n            lastName\\n            allocations(first: 1, budgetId: $budgetId) {\\n              edges {\\n                node {\\n                  id\\n                  recurringAmount\\n                  balance\\n                  type\\n                  __typename\\n                }\\n                __typename\\n              }\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment BudgetHeaderChart on Budget {\\n  id\\n  currentGoal\\n  expiresAt\\n  recurringAmount\\n  shareBudgetFunds\\n  totalClearedForBudgetPeriod\\n  totalDivviedForBudgetPeriod\\n  totalPendingForBudgetPeriod\\n  type\\n  __typename\\n}\\n\"}";
        bodyParams = new String[]{config.getBudgetId()};
        String referer = String.format("https://app.divvy.co/budgets/%s/recurring-funds", config.getBudgetId());
        defaultHeader.put("referer", referer);
    }

    //返回 获取allocationId
    //{"data":{"node":{"users":{"edges":[{"role":"MANAGER","node":{"lastName":"SITK","id":"VXNlcjo1MTIzNg==","firstName":"MING","displayName":"MING SITK","avatarUrl":null,"allocations":{"edges":[{"node":{"type":"ONE_TIME","recurringAmount":null,"id":"VXNlckFsbG9jYXRpb246NDQxNTY3","balance":2700,"__typename":"UserAllocation"},"__typename":"UserAllocationEdge"}],"__typename":"UserAllocationConnection"},"__typename":"User"},"__typename":"BudgetToUsersEdge"}],"__typename":"BudgetToUsersConnection"},"type":"ONE_TIME","totalPendingForBudgetPeriod":0,"totalDivviedForBudgetPeriod":3703,"totalClearedForBudgetPeriod":0,"shareBudgetFunds":false,"recurringAmount":10000,"id":"QnVkZ2V0OjQ3MzAz","expiresAt":null,"currentGoal":10000,"allCards":{"edges":[{"node":{"userAllocation":{"type":"RECURRING","recurringAmount":1,"id":"VXNlckFsbG9jYXRpb246NDQ1NTgy","expiresAt":null,"balance":1,"__typename":"UserAllocation"},"name":"ralf","latestTransaction":null,"lastFour":"1173","id":"Q2FyZDozNDU1NTY=","cardType":"SUBSCRIPTION","__typename":"Card"},"__typename":"CardEdge"},{"node":{"userAllocation":{"type":"RECURRING","recurringAmount":1,"id":"VXNlckFsbG9jYXRpb246NDQ1NTM2","expiresAt":null,"balance":1,"__typename":"UserAllocation"},"name":"ralfbawg","latestTransaction":null,"lastFour":"0580","id":"Q2FyZDozNDU0OTg=","cardType":"SUBSCRIPTION","__typename":"Card"},"__typename":"CardEdge"},{"node":{"userAllocation":{"type":"RECURRING","recurringAmount":1,"id":"VXNlckFsbG9jYXRpb246NDQ1MzM4","expiresAt":null,"balance":1,"__typename":"UserAllocation"},"name":"ralfchen","latestTransaction":null,"lastFour":"9187","id":"Q2FyZDozNDUzNTc=","cardType":"SUBSCRIPTION","__typename":"Card"},"__typename":"CardEdge"},{"node":{"userAllocation":{"type":"ONE_TIME","recurringAmount":null,"id":"VXNlckFsbG9jYXRpb246NDYxNjgy","expiresAt":1565593200,"balance":1000,"__typename":"UserAllocation"},"name":"Terrence Bryant","latestTransaction":null,"lastFour":"9691","id":"Q2FyZDozNTg1MzQ=","cardType":"BURNER","__typename":"Card"},"__typename":"CardEdge"}],"__typename":"CardConnection"},"__typename":"Budget"}}}
    @Override
    public SetBudgetCardRecurringRsp persistent(String rsp) {
        return null;
    }
}

